<a href="https://colab.research.google.com/github/Halak29-6/AI_ML-Training-Batch1/blob/main/Classwork/Data_Cleaning_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data collection**

1 databse , warehouse

2 api

3 web scrapping

4 websites, raw data, kaggle, etc

In [ ]:
import pandas as pd

In [ ]:
df_1 = pd.DataFrame({'ID':[1,2,3,4] ,
                      'Class':[5,7,8,9] })
df_1

   ID  Class
0   1      5
1   2      7
2   3      8
3   4      9

In [ ]:
df_2 = pd.DataFrame({'ID':[1,2,3,5] ,
                      'Name':['a','b','c','d'] })
df_2

   ID Name
0   1    a
1   2    b
2   3    c
3   5    d

In [ ]:
df_3 = pd.merge(df_1,df_2)

In [ ]:
df_3

   ID  Class Name
0   1      5    a
1   2      7    b
2   3      8    c

In [ ]:
df_3 = pd.merge(df_1,df_2,on='ID',how='inner')
df_3

   ID  Class Name
0   1      5    a
1   2      7    b
2   3      8    c

In [ ]:
df_3 = pd.merge(df_1,df_2,on='ID',how='outer')
df_3

   ID  Class Name
0   1    5.0    a
1   2    7.0    b
2   3    8.0    c
3   4    9.0  NaN
4   5    NaN    d

In [ ]:
df_3 = pd.merge(df_1,df_2,on='ID',how='left')
df_3

   ID  Class Name
0   1      5    a
1   2      7    b
2   3      8    c
3   4      9  NaN

In [ ]:
df_3 = pd.merge(df_1,df_2,on='ID',how='right')
df_3

   ID  Class Name
0   1    5.0    a
1   2    7.0    b
2   3    8.0    c
3   5    NaN    d

In [ ]:
dfIndex = pd.DataFrame({'ID':[1,2,3,5] ,
                      'Name':['a','b','c','d'] } , index=[9099,8088,7077,6066])
dfIndex

      ID Name
9099   1    a
8088   2    b
7077   3    c
6066   5    d

In [ ]:
dfIndex1 = pd.DataFrame({'ID':[1,2,3,4] ,
                      'Class':[1,2,3,4] } , index=[9099,8088,7077,6066])
dfIndex1

      ID  Class
9099   1      1
8088   2      2
7077   3      3
6066   4      4

In [ ]:
dfIndexMerge = pd.merge(dfIndex,dfIndex1,on='ID',how='left' ,indicator=True)

In [ ]:
dfIndexMerge

   ID Name  Class     _merge
0   1    a    1.0       both
1   2    b    2.0       both
2   3    c    3.0       both
3   5    d    NaN  left_only

In [ ]:
dfIndexMerge = pd.merge(dfIndex,dfIndex1,left_index= True ,right_index=True)

In [ ]:
dfIndexMerge

      ID_x Name  ID_y  Class
9099     1    a     1      1
8088     2    b     2      2
7077     3    c     3      3
6066     5    d     4      4

In [ ]:
dfFruit = pd.DataFrame({'amt':[10,20,30] ,
                         'fruit':["apple","banana","cherry"]} ,
                       index = [10,20,30])
dfFruit

    amt   fruit
10   10   apple
20   20  banana
30   30  cherry

In [ ]:
dfveg = pd.DataFrame({'amt':[10,20,30] ,
                         'veg':["potato","onion","lady Finger"]} ,
                       index = [100,200,300])
dfveg

     amt          veg
100   10       potato
200   20        onion
300   30  lady Finger

In [ ]:
dfMergeF_V1 = pd.merge(dfFruit,dfveg,left_index=True,right_index=True)
dfMergeF_V1

Empty DataFrame
Columns: [amt_x, fruit, amt_y, veg]
Index: []

In [ ]:
dfFruit = pd.DataFrame({'amt':[10,20,30] ,
                         'fruit':["apple","banana","cherry"]} ,
                       index = [10,20,30])
dfFruit

    amt   fruit
10   10   apple
20   20  banana
30   30  cherry

In [ ]:
dfveg = pd.DataFrame({'amt':[10,20,30] ,
                         'veg':["potato","onion","lady Finger"]} ,
                       index = [10,20,30])
dfveg

    amt          veg
10   10       potato
20   20        onion
30   30  lady Finger

In [ ]:
dfMergeF_V = pd.merge(dfFruit,dfveg,left_index=True,right_index=True)
dfMergeF_V

    amt_x   fruit  amt_y          veg
10     10   apple     10       potato
20     20  banana     20        onion
30     30  cherry     30  lady Finger

***Handling missing values***

In [ ]:
import numpy as np

In [ ]:
data = {
    'Age': [23,np.nan,20,18,np.nan],
    'Score':[56,87,23,np.nan,57],
    'City':['ny','paris','london',np.nan,'rome']
}
dataf= pd.DataFrame(data)
print("Original data:\n\n",dataf)
# is null , not null , nan ,

Original data:

     Age  Score    City
0  23.0   56.0      ny
1   NaN   87.0   paris
2  20.0   23.0  london
3  18.0    NaN     NaN
4   NaN   57.0    rome

In [ ]:
print(dataf.isnull())

     Age  Score   City
0  False  False  False
1   True  False  False
2  False  False  False
3  False   True   True
4   True  False  False

In [ ]:
print(dataf.isnull().sum())

Age      2
Score    1
City     1
dtype: int64

In [ ]:
print(dataf.isnull().sum().sum())

4

In [ ]:
print(dataf.notnull())

     Age  Score   City
0   True   True   True
1  False   True   True
2   True   True   True
3   True  False  False
4  False   True   True

***Delete missing values***

In [ ]:
df_clean_rows = dataf.dropna()
df_clean_cols = dataf.dropna(axis=1)
df_clean_subset = dataf.dropna(subset=['Age'])

In [ ]:
df_clean_rows

    Age  Score    City
0  23.0   56.0      ny
2  20.0   23.0  london

In [ ]:
df_clean_cols

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [ ]:
df_clean_subset

    Age  Score    City
0  23.0   56.0      ny
2  20.0   23.0  london
3  18.0    NaN     NaN

In [ ]:
df_zero = dataf.fillna(0)

In [ ]:
dataf['Age'] = dataf['Age'].fillna(dataf['Age'].mean())

In [ ]:
dataf['City'] = dataf['City'].fillna(dataf['City'].mode()[0])

In [ ]:
df_zero

    Age  Score    City
0  23.0   56.0      ny
1   0.0   87.0   paris
2  20.0   23.0  london
3  18.0    0.0       0
4   0.0   57.0    rome

In [ ]:
dataf['Age']

0    23.000000
1    20.333333
2    20.000000
3    18.000000
4    20.333333
Name: Age, dtype: float64

In [ ]:
dataf['City']

0        ny
1     paris
2    london
3    london
4      rome
Name: City, dtype: object

In [ ]:
dataf['Score']

0    56.0
1    87.0
2    23.0
3     NaN
4    57.0
Name: Score, dtype: float64

**Time-Series Interpolation**

In [ ]:
df_ffill = dataf.ffill()

In [ ]:
df_bfill = dataf.bfill()

In [ ]:
df_interp = dataf.select_dtypes(include=[np.number]).interpolate()

In [ ]:
df_ffill

         Age  Score    City
0  23.000000   56.0      ny
1  20.333333   87.0   paris
2  20.000000   23.0  london
3  18.000000   23.0  london
4  20.333333   57.0    rome

In [ ]:
df_bfill

         Age  Score    City
0  23.000000   56.0      ny
1  20.333333   87.0   paris
2  20.000000   23.0  london
3  18.000000   57.0  london
4  20.333333   57.0    rome

In [ ]:
df_interp

         Age  Score
0  23.000000   56.0
1  20.333333   87.0
2  20.000000   23.0
3  18.000000   40.0
4  20.333333   57.0

data preprocessing , difference btwn data & information , structures & unstructured data

ML/AI algo follow the rule of *** (GIGO) Garbage In and Garbage out***

***Data preprocessing steps:***

Data cleaning ,Data integration ,Data reduction ,Data transformation ,Data discretization

In [ ]:
import pandas as pd

In [ ]:
df_1 = pd.DataFrame({'ID':[1,2,3,4] ,
                      'Class':[5,7,8,9] })
df_1

   ID  Class
0   1      5
1   2      7
2   3      8
3   4      9

In [ ]:
df_2 = pd.DataFrame({'ID':[1,2,3,5] ,
                      'Name':['a','b','c','d'] })
df_2

   ID Name
0   1    a
1   2    b
2   3    c
3   5    d

In [ ]:
df_3 = pd.merge(df_1,df_2)

In [ ]:
df_3

   ID  Class Name
0   1      5    a
1   2      7    b
2   3      8    c

In [ ]:
df_3 = pd.merge(df_1,df_2,on='ID',how='inner')
df_3

   ID  Class Name
0   1      5    a
1   2      7    b
2   3      8    c

In [ ]:
df_3 = pd.merge(df_1,df_2,on='ID',how='outer')
df_3

   ID  Class Name
0   1    5.0    a
1   2    7.0    b
2   3    8.0    c
3   4    9.0  NaN
4   5    NaN    d

In [ ]:
df_3 = pd.merge(df_1,df_2,on='ID',how='left')
df_3

   ID  Class Name
0   1      5    a
1   2      7    b
2   3      8    c
3   4      9  NaN

In [ ]:
df_3 = pd.merge(df_1,df_2,on='ID',how='right')
df_3

   ID  Class Name
0   1    5.0    a
1   2    7.0    b
2   3    8.0    c
3   5    NaN    d

In [ ]:
dfIndex = pd.DataFrame({'ID':[1,2,3,5] ,
                      'Name':['a','b','c','d'] } , index=[9099,8088,7077,6066])
dfIndex

      ID Name
9099   1    a
8088   2    b
7077   3    c
6066   5    d

In [ ]:
dfIndex1 = pd.DataFrame({'ID':[1,2,3,4] ,
                      'Class':[1,2,3,4] } , index=[9099,8088,7077,6066])
dfIndex1

      ID  Class
9099   1      1
8088   2      2
7077   3      3
6066   4      4

In [ ]:
dfIndexMerge = pd.merge(dfIndex,dfIndex1,on='ID',how='left' ,indicator=True)

In [ ]:
dfIndexMerge

   ID Name  Class     _merge
0   1    a    1.0       both
1   2    b    2.0       both
2   3    c    3.0       both
3   5    d    NaN  left_only

In [ ]:
dfIndexMerge = pd.merge(dfIndex,dfIndex1,left_index= True ,right_index=True)

In [ ]:
dfIndexMerge

      ID_x Name  ID_y  Class
9099     1    a     1      1
8088     2    b     2      2
7077     3    c     3      3
6066     5    d     4      4

In [ ]:
dfFruit = pd.DataFrame({'amt':[10,20,30] ,
                         'fruit':["apple","banana","cherry"]} ,
                       index = [10,20,30])
dfFruit

    amt   fruit
10   10   apple
20   20  banana
30   30  cherry

In [ ]:
dfveg = pd.DataFrame({'amt':[10,20,30] ,
                         'veg':["potato","onion","lady Finger"]} ,
                       index = [100,200,300])
dfveg

     amt          veg
100   10       potato
200   20        onion
300   30  lady Finger

In [ ]:
dfMergeF_V1 = pd.merge(dfFruit,dfveg,left_index=True,right_index=True)
dfMergeF_V1

Empty DataFrame
Columns: [amt_x, fruit, amt_y, veg]
Index: []

In [ ]:
dfFruit = pd.DataFrame({'amt':[10,20,30] ,
                         'fruit':["apple","banana","cherry"]} ,
                       index = [10,20,30])
dfFruit

    amt   fruit
10   10   apple
20   20  banana
30   30  cherry

In [ ]:
dfveg = pd.DataFrame({'amt':[10,20,30] ,
                         'veg':["potato","onion","lady Finger"]} ,
                       index = [10,20,30])
dfveg

    amt          veg
10   10       potato
20   20        onion
30   30  lady Finger

In [ ]:
dfMergeF_V = pd.merge(dfFruit,dfveg,left_index=True,right_index=True)
dfMergeF_V

    amt_x   fruit  amt_y          veg
10     10   apple     10       potato
20     20  banana     20        onion
30     30  cherry     30  lady Finger

***Handling missing values***

In [ ]:
import numpy as np

In [ ]:
data = {
    'Age': [23,np.nan,20,18,np.nan],
    'Score':[56,87,23,np.nan,57],
    'City':['ny','paris','london',np.nan,'rome']
}
dataf= pd.DataFrame(data)
print("Original data:\n\n",dataf)
# is null , not null , nan ,

Original data:

     Age  Score    City
0  23.0   56.0      ny
1   NaN   87.0   paris
2  20.0   23.0  london
3  18.0    NaN     NaN
4   NaN   57.0    rome

In [ ]:
print(dataf.isnull())

     Age  Score   City
0  False  False  False
1   True  False  False
2  False  False  False
3  False   True   True
4   True  False  False

In [ ]:
print(dataf.isnull().sum())

Age      2
Score    1
City     1
dtype: int64

In [ ]:
print(dataf.isnull().sum().sum())

4

In [ ]:
print(dataf.notnull())

     Age  Score   City
0   True   True   True
1  False   True   True
2   True   True   True
3   True  False  False
4  False   True   True

***Delete missing values***

In [ ]:
df_clean_rows = dataf.dropna()
df_clean_cols = dataf.dropna(axis=1)
df_clean_subset = dataf.dropna(subset=['Age'])

In [ ]:
df_clean_rows

    Age  Score    City
0  23.0   56.0      ny
2  20.0   23.0  london

In [ ]:
df_clean_cols

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [ ]:
df_clean_subset

    Age  Score    City
0  23.0   56.0      ny
2  20.0   23.0  london
3  18.0    NaN     NaN

***Impute(FILL) missing data***