<a href="https://colab.research.google.com/github/Halak29-6/AI_ML-Training-Batch1/blob/main/Classwork/PandasBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**10/07/2026**

Introduction to Pandas, applications of pandas and basics

Pandas functions and basic data manipulation

Data analysis with pandas

In [1]:
import pandas as pd

In [2]:
df_1 = pd.read_csv('Social_Network_Ads.csv')

In [3]:
df_1

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
pd.__version__

'2.2.2'

# Series

In [5]:
scalar_s = pd.Series(1)
print(scalar_s)

0    1
dtype: int64

In [6]:
scalar_s1 = pd.Series(0.2, index = [1,2,3,4])
print(scalar_s1)

1    0.2
2    0.2
3    0.2
4    0.2
dtype: float64

# Empty series

In [ ]:
empty_s = pd.Series([])

type(empty_s)

empty_s

Series([], dtype: object)

# list -> Series

In [8]:
list_s = [1,2,-5,3.0,'data']
print(list_s)
type(list_s)

[1, 2, -5, 3.0, 'data']

list

In [9]:
series = pd.Series(list_s)
print(series)

0       1
1       2
2      -5
3     3.0
4    data
dtype: object

In [10]:
type(series)

pandas.core.series.Series

# dictionary to Series

In [ ]:
dict_s = pd.Series({'a' : 1 , 'b': 2})
dict_s

a    1
b    2
dtype: int64

In [11]:
dict2 = {'ID' : [1,2,3,4],
        "name": ['apple', 'banna', 'guava','cherry']}
dict2

{'ID': [1, 2, 3, 4], 'name': ['apple', 'banna', 'guava', 'cherry']}

In [12]:
df_dict_s = pd.Series(dict2)
df_dict_s

ID                       [1, 2, 3, 4]
name    [apple, banna, guava, cherry]
dtype: object

In [ ]:
series_1 = pd.Series([2,3,4,5], index = ['a','b','c','d'])
print(series_1)

a    2
b    3
c    4
d    5
dtype: int64

In [13]:
#chaging data type

series_2 = pd.Series([1,2,3,4], index = ['b','y','t','e'], dtype = float, name = 'data')
print(series_2)

# 'name' parameter

b    1.0
y    2.0
t    3.0
e    4.0
Name: data, dtype: float64

# indexing in series

In [14]:
sr_indx = pd.Series([1,2,3,4,5])
print(sr_indx)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [15]:
sr_indx[0]

np.int64(1)

In [ ]:

sr_indx[1]

np.int64(2)

In [ ]:
min(sr_indx)

1

In [ ]:
max(sr_indx)

5

# DataFrame

In [16]:
emt_df = pd.DataFrame()
print(emt_df)

Empty DataFrame
Columns: []
Index: []

# list to DataFrame

In [ ]:
lst = ['a','b','c']
print(lst)

['a', 'b', 'c']

In [ ]:
df_1 = pd.DataFrame(lst)
df_1

   0
0  a
1  b
2  c

In [ ]:
ls_of_ls = [[1,2,3],[1,23,45],[5,2,4]]
print(ls_of_ls)

[[1, 2, 3], [1, 23, 45], [5, 2, 4]]

In [ ]:
df_2 = pd.DataFrame(ls_of_ls)
df_2

   0   1   2
0  1   2   3
1  1  23  45
2  5   2   4

# dict to dataframe

In [ ]:
dict1 = {'ID' : [1,2,3,4]}
dict1

{'ID': [1, 2, 3, 4]}

In [ ]:
df_dict1 = pd.DataFrame(dict1)

df_dict1

   ID
0   1
1   2
2   3
3   4

In [17]:
dict2 = {'ID' : [1,2,3,4],
        "name": ['car', 'van', 'jeep','cycle']}
dict2

{'ID': [1, 2, 3, 4], 'name': ['car', 'van', 'jeep', 'cycle']}

In [18]:
df_dict2 = pd.DataFrame(dict2)
df_dict2

   ID   name
0   1    car
1   2    van
2   3   jeep
3   4  cycle

In [19]:
dict_1 = [{'a':1, 'b':2}, {'a':3, 'b':4}]
dict_1

[{'a': 1, 'b': 2}, {'a': 3, 'b': 4}]

In [ ]:
df_dict_1 = pd.DataFrame(dict_1)
df_dict_1

   a  b
0  1  2
1  3  4

In [20]:
dict_2 = [{'a':1, 'b':2}, {'a':3, 'b':4, 'c': 44}]
dict_2

[{'a': 1, 'b': 2}, {'a': 3, 'b': 4, 'c': 44}]

In [21]:
df_dict_2 = pd.DataFrame(dict_2)
df_dict_2

   a  b     c
0  1  2   NaN
1  3  4  44.0

# data importing/ reading

In [ ]:
pd.read_csv("E:\Data set\Pandas_dataset_prac\student_results.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Data set\\Pandas_dataset_prac\\student_results.csv'

In [ ]:
import os
print(os.getcwd())

In [23]:
df = pd.read_csv("Social_Network_Ads.csv", nrows = 1)
df

    User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0

In [25]:
df = pd.read_csv("/content/Social_Network_Ads.csv", nrows = 3)
df

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0

In [26]:
df = pd.read_csv("/content/Social_Network_Ads.csv", usecols = [1])
df

     Gender
0      Male
1      Male
2    Female
3    Female
4      Male
..      ...
395  Female
396    Male
397  Female
398    Male
399  Female

[400 rows x 1 columns]

In [28]:
df = pd.read_csv("/content/Social_Network_Ads.csv", usecols = [1,2,3])
df

     Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

In [29]:
df = pd.read_csv("/content/Social_Network_Ads.csv", usecols = [1,4])
df

     Gender  Purchased
0      Male          0
1      Male          0
2    Female          0
3    Female          0
4      Male          0
..      ...        ...
395  Female          1
396    Male          1
397  Female          1
398    Male          0
399  Female          1

[400 rows x 2 columns]

In [ ]:
df = pd.read_csv("/content/Social_Network_Ads.csv", skiprows = 1)
df

,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
2,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
3,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
4,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
5,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
6,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
7,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
8,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [30]:
df = pd.read_csv("/content/Social_Network_Ads.csv", skiprows = [1,3,4])
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15810944    Male   35            20000          0
1    15804002    Male   19            76000          0
2    15728773    Male   27            58000          0
3    15598044  Female   27            84000          0
4    15694829  Female   32           150000          1
..        ...     ...  ...              ...        ...
392  15691863  Female   46            41000          1
393  15706071    Male   51            23000          1
394  15654296  Female   50            20000          1
395  15755018    Male   36            33000          0
396  15594041  Female   49            36000          1

[397 rows x 5 columns]

In [ ]:
df = pd.read_csv("/content/Social_Network_Ads.csv", index_col = 'ID')
df

,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,
1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [ ]:
df = pd.read_csv("/content/Social_Network_Ads.csv", index_col = 'Name')
df

,ID,Industry,Inception,Revenue,Expenses,Profit,Growth
Name,,,,,,,
Lamtone,1,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
Stripfind,2,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
Canecorporation,3,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
Mattouch,4,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
Techdrill,5,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
Techline,6,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
Cityace,7,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
Kayelectronics,8,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
Ganzlax,9,IT Services,2011,"$14,001,180",NaN,11901180,18%
Trantraxlax,10,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [ ]:
df = pd.read_csv("/content/Social_Network_Ads.csv", index_col = 3)
df

,ID,Name,Industry,Revenue,Expenses,Profit,Growth
Inception,,,,,,,
2009,1,Lamtone,IT Services,"$11,757,018","6,482,465 Dollars",5274553,30%
2010,2,Stripfind,Financial Services,"$12,329,371","916,455 Dollars",11412916,20%
2012,3,Canecorporation,Health,"$10,597,009","7,591,189 Dollars",3005820,7%
2013,4,Mattouch,IT Services,"$14,026,934","7,429,377 Dollars",6597557,26%
2009,5,Techdrill,Health,"$10,573,990","7,435,363 Dollars",3138627,8%
2006,6,Techline,Health,"$13,898,119","5,470,303 Dollars",8427816,23%
2010,7,Cityace,Health,"$9,254,614","6,249,498 Dollars",3005116,6%
2009,8,Kayelectronics,Health,"$9,451,943","3,878,113 Dollars",5573830,4%
2011,9,Ganzlax,IT Services,"$14,001,180",NaN,11901180,18%
2011,10,Trantraxlax,Government Services,"$11,088,336","5,635,276 Dollars",5453060,7%

# header

In [31]:
df = pd.read_csv("/content/Social_Network_Ads.csv", header = 1)
df

     15624510    Male  19  19000  0
0    15810944    Male  35  20000  0
1    15668575  Female  26  43000  0
2    15603246  Female  27  57000  0
3    15804002    Male  19  76000  0
4    15728773    Male  27  58000  0
..        ...     ...  ..    ... ..
394  15691863  Female  46  41000  1
395  15706071    Male  51  23000  1
396  15654296  Female  50  20000  1
397  15755018    Male  36  33000  0
398  15594041  Female  49  36000  1

[399 rows x 5 columns]

In [32]:
df = pd.read_csv("/content/Social_Network_Ads.csv", header = None)
df

            0       1    2                3          4
0     User ID  Gender  Age  EstimatedSalary  Purchased
1    15624510    Male   19            19000          0
2    15810944    Male   35            20000          0
3    15668575  Female   26            43000          0
4    15603246  Female   27            57000          0
..        ...     ...  ...              ...        ...
396  15691863  Female   46            41000          1
397  15706071    Male   51            23000          1
398  15654296  Female   50            20000          1
399  15755018    Male   36            33000          0
400  15594041  Female   49            36000          1

[401 rows x 5 columns]

In [33]:
df = pd.read_csv("/content/Social_Network_Ads.csv", names = ['A','B'])
df

                                   A          B
User ID  Gender Age  EstimatedSalary  Purchased
15624510 Male   19             19000          0
15810944 Male   35             20000          0
15668575 Female 26             43000          0
15603246 Female 27             57000          0
...                              ...        ...
15691863 Female 46             41000          1
15706071 Male   51             23000          1
15654296 Female 50             20000          1
15755018 Male   36             33000          0
15594041 Female 49             36000          1

[401 rows x 2 columns]

In [34]:
df = pd.read_csv("/content/Social_Network_Ads.csv", dtype = {'ID': 'float64', 'profit' : 'float64'})
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [35]:
df = pd.read_csv("/content/Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [36]:
df = pd.read_csv("/content/Social_Network_Ads.csv", na_values = 'not available')
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [37]:
df = pd.read_csv("/content/Social_Network_Ads.csv", na_values = 'not available')
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [38]:
df.isnull()

     User ID  Gender    Age  EstimatedSalary  Purchased
0      False   False  False            False      False
1      False   False  False            False      False
2      False   False  False            False      False
3      False   False  False            False      False
4      False   False  False            False      False
..       ...     ...    ...              ...        ...
395    False   False  False            False      False
396    False   False  False            False      False
397    False   False  False            False      False
398    False   False  False            False      False
399    False   False  False            False      False

[400 rows x 5 columns]

In [39]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [40]:
df.isnull().sum().sum()

np.int64(0)

In [41]:
df.notnull()

     User ID  Gender   Age  EstimatedSalary  Purchased
0       True    True  True             True       True
1       True    True  True             True       True
2       True    True  True             True       True
3       True    True  True             True       True
4       True    True  True             True       True
..       ...     ...   ...              ...        ...
395     True    True  True             True       True
396     True    True  True             True       True
397     True    True  True             True       True
398     True    True  True             True       True
399     True    True  True             True       True

[400 rows x 5 columns]

In [42]:
df.notnull().sum()

User ID            400
Gender             400
Age                400
EstimatedSalary    400
Purchased          400
dtype: int64

In [43]:
df.notnull().sum().sum()

np.int64(2000)

In [44]:
import numpy as np
ser = pd.Series([1,2,3,np.nan, 4,np.nan])
ser

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

In [45]:
ser.isnull()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [46]:
df = pd.read_csv("/content/Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [47]:
df.dropna()

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [48]:
df.dropna(axis = 1)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [49]:
df.dropna(axis = 0)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [50]:
#any - work like dropna

df.dropna(how = 'any')

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [51]:
df.dropna(axis = 1,how = 'any')

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [52]:
#all num row and values
df.dropna(how = 'all')

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [53]:
df.dropna(thresh = 2)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [54]:
# row fillingA

df.fillna(method = 'ffill', axis = 0)

/tmp/ipykernel_1665/369254934.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill', axis = 0)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [55]:
# colums axis = 1


df.fillna(method = 'ffill', axis = 1)

/tmp/ipykernel_1665/2916554109.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill', axis = 1)

      User ID  Gender Age EstimatedSalary Purchased
0    15624510    Male  19           19000         0
1    15810944    Male  35           20000         0
2    15668575  Female  26           43000         0
3    15603246  Female  27           57000         0
4    15804002    Male  19           76000         0
..        ...     ...  ..             ...       ...
395  15691863  Female  46           41000         1
396  15706071    Male  51           23000         1
397  15654296  Female  50           20000         1
398  15755018    Male  36           33000         0
399  15594041  Female  49           36000         1

[400 rows x 5 columns]

In [56]:
df.fillna(55, limit = 1) # columns vise / limit only use with method

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [57]:
df.fillna(method = 'ffill' , limit = 2, axis = 0)

/tmp/ipykernel_1665/1232737886.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill' , limit = 2, axis = 0)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [58]:
df.fillna(method = 'ffill' , limit = 2, axis = 1)

/tmp/ipykernel_1665/3002877853.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill' , limit = 2, axis = 1)

      User ID  Gender Age EstimatedSalary Purchased
0    15624510    Male  19           19000         0
1    15810944    Male  35           20000         0
2    15668575  Female  26           43000         0
3    15603246  Female  27           57000         0
4    15804002    Male  19           76000         0
..        ...     ...  ..             ...       ...
395  15691863  Female  46           41000         1
396  15706071    Male  51           23000         1
397  15654296  Female  50           20000         1
398  15755018    Male  36           33000         0
399  15594041  Female  49           36000         1

[400 rows x 5 columns]

# replace()
to_replace , limit, value, regex, inplace, method

In [61]:
df = pd.read_csv("student_results.csv")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [62]:
# fill only numeric values not char

df.interpolate()

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [63]:
df.interpolate(method = 'linear')

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [64]:
df = pd.read_csv("student_results.csv", parse_dates = ['Study hrs'], index_col = 'Class')
df

/tmp/ipykernel_1665/187982824.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("student_results.csv", parse_dates = ['Study hrs'], index_col = 'Class')

,Student ID,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Class,,,,,,
10,1001,2,9,3,5,50
10,1002,6,8,2,0,80
10,1003,3,8,2,4,60
11,1004,0,10,1,5,45
11,1005,4,7,2,0,75
11,1006,10,7,0,0,96
12,1007,4,6,0,0,80
12,1008,10,6,2,0,90
12,1009,2,8,2,4,60
12,1010,6,9,1,0,85

In [ ]:
# df.interpolate(method = 'nearest')

# loc and iloc

Access a group of rows & columns by label(s) or boolean array.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\student_results.csv")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [ ]:
df.loc[:]

,Student ID,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Class,,,,,,
10.0,1001,2,9.0,3.0,5,50.0
10.0,1002,6,8.0,2.0,0,80.0
10.0,1003,NaN,NaN,2.0,4,60.0
11.0,1004,NaN,NaN,1.0,5,45.0
11.0,1005,NaN,NaN,2.0,0,NaN
11.0,1006,10,7.0,0.0,0,NaN
NaN,1007,4,6.0,0.0,0,NaN
NaN,1008,10,NaN,NaN,0,90.0
12.0,1009,2,8.0,2.0,4,60.0
12.0,1010,6,9.0,1.0,0,85.0

In [ ]:
df.loc[0]

Student ID                1001
Class                       10
Study hrs                    2
Sleeping hrs                 9
Social Media usage hrs       3
Mobile Games hrs             5
Percantege                  50
Name: 0, dtype: int64

In [ ]:
df.loc[1]

Student ID                1002
Class                       10
Study hrs                    6
Sleeping hrs                 8
Social Media usage hrs       2
Mobile Games hrs             0
Percantege                  80
Name: 1, dtype: int64

In [ ]:
df.loc[[0,1]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80

In [ ]:
df.loc[[2,4]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
2,1003,10,3,8,2,4,60
4,1005,11,4,7,2,0,75

In [ ]:
df.loc[4, 'Class']

np.int64(11)

In [ ]:
df.loc[0:3, 'Class']

0    10
1    10
2    10
3    11
Name: Class, dtype: int64

In [ ]:
df.loc[0:2, 'Percantege']

0    50
1    80
2    60
Name: Percantege, dtype: int64

In [ ]:
df

,Student ID,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Class,,,,,,
10.0,1001,2,9.0,3.0,5,50.0
10.0,1002,6,8.0,2.0,0,80.0
10.0,1003,NaN,NaN,2.0,4,60.0
11.0,1004,NaN,NaN,1.0,5,45.0
11.0,1005,NaN,NaN,2.0,0,NaN
11.0,1006,10,7.0,0.0,0,NaN
NaN,1007,4,6.0,0.0,0,NaN
NaN,1008,10,NaN,NaN,0,90.0
12.0,1009,2,8.0,2.0,4,60.0
12.0,1010,6,9.0,1.0,0,85.0

In [ ]:
df.loc[df['Class'] <11]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60

In [ ]:
df.loc[df['Class'] <11, ['Percantege']]

   Percantege
0          50
1          80
2          60

In [ ]:
# integer location based indexing

In [ ]:
df.iloc[0]

Student ID                1001
Class                       10
Study hrs                    2
Sleeping hrs                 9
Social Media usage hrs       3
Mobile Games hrs             5
Percantege                  50
Name: 0, dtype: int64

In [ ]:
 df.iloc[[0]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50

In [ ]:
df

,Student ID,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Class,,,,,,
10.0,1001,2,9.0,3.0,5,50.0
10.0,1002,6,8.0,2.0,0,80.0
10.0,1003,NaN,NaN,2.0,4,60.0
11.0,1004,NaN,NaN,1.0,5,45.0
11.0,1005,NaN,NaN,2.0,0,NaN
11.0,1006,10,7.0,0.0,0,NaN
NaN,1007,4,6.0,0.0,0,NaN
NaN,1008,10,NaN,NaN,0,90.0
12.0,1009,2,8.0,2.0,4,60.0
12.0,1010,6,9.0,1.0,0,85.0

In [ ]:
df.iloc[:,0]

0    1001
1    1002
2    1003
3    1004
4    1005
5    1006
6    1007
7    1008
8    1009
9    1010
Name: Student ID, dtype: int64

In [ ]:
df.iloc[[0,1]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80

# groupby

pandas groupby function is used ot split the data into groups based on some creiteria

- splitting the object
- applying the function
- combining the result

In [ ]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\student_results GROUP BY.csv")
df

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
0        1001       A     10          2                       3          50
1        1002       B     10          6                       2          80
2        1003       A     10          3                       2          60
3        1004       C     11          0                       1          45
4        1005       C     12          5                       2          75

In [ ]:
gr1 = df.groupby(by = 'Section')
gr1

In [ ]:
gr1.groups

{'A': [0, 2], 'B': [1], 'C': [3, 4]}

In [ ]:
df.groupby(['Section', 'Class']).groups

{('A', 10): [0, 2], ('B', 10): [1], ('C', 11): [3], ('C', 12): [4]}

In [ ]:
for Section, df_1 in gr1:
    print(Section)
    print(df_1)

A
   Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
0        1001       A     10          2                       3          50
2        1003       A     10          3                       2          60
B
   Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
1        1002       B     10          6                       2          80
C
   Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
3        1004       C     11          0                       1          45
4        1005       C     12          5                       2          75

In [ ]:
list(gr1)

[('A',
     Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
  0        1001       A     10          2                       3          50
  2        1003       A     10          3                       2          60),
 ('B',
     Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
  1        1002       B     10          6                       2          80),
 ('C',
     Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
  3        1004       C     11          0                       1          45
  4        1005       C     12          5                       2          75)]

In [ ]:
dict(list(gr1))

{'A':    Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
 0        1001       A     10          2                       3          50
 2        1003       A     10          3                       2          60,
 'B':    Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
 1        1002       B     10          6                       2          80,
 'C':    Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
 3        1004       C     11          0                       1          45
 4        1005       C     12          5                       2          75}

In [ ]:
df.groupby('Class').get_group(10)

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
0        1001       A     10          2                       3          50
1        1002       B     10          6                       2          80
2        1003       A     10          3                       2          60

In [ ]:
df.groupby('Section').get_group('A')

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
0        1001       A     10          2                       3          50
2        1003       A     10          3                       2          60

In [ ]:
gr1.sum()

         Student ID  Class  Study hrs  Social Media usage hrs  Percantege
Section
A              2004     20          5                       5         110
B              1002     10          6                       2          80
C              2009     23          5                       3         120

# Merg

In [ ]:
df1 = pd.DataFrame({ 'ID' : [1,2,34,4],
                     'Class' : [5,6,7,8]})
df1

   ID  Class
0   1      5
1   2      6
2  34      7
3   4      8

In [ ]:
df2 = pd.DataFrame({ 'ID' : [1,2,3,4],
                     "Name" : ['A','B','C','D']})
df2

   ID Name
0   1    A
1   2    B
2   3    C
3   4    D

In [ ]:
pd.merge(df1,df2)

   ID  Class Name
0   1      5    A
1   2      6    B
2   4      8    D

In [ ]:
pd.merge(df1,df2, on = "ID")

   ID  Class Name
0   1      5    A
1   2      6    B
2   4      8    D

In [ ]:
pd.merge(df2,df1, on = "ID")

   ID Name  Class
0   1    A      5
1   2    B      6
2   4    D      8

In [ ]:
# intersection = inner , same as merge on id(same valuse merge different value not)
pd.merge(df1,df2, on = 'ID' , how = 'inner')

   ID  Class Name
0   1      5    A
1   2      6    B
2   4      8    D

# Concat()

padas provides various facilities for easily combining together Series, DataFrame and panel objects

In [ ]:
sr1 = pd.Series([0,1,2])
sr1

0    0
1    1
2    2
dtype: int64

In [ ]:
df2 = pd.DataFrame({ "ID" : [5,6,7,8],
                     'Name' : ['E','F','G','H'],
                     'Class' : [9,10,11,12]})
df2

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [ ]:
pd.concat([df1,df2])

   ID Name  Class
0   1    A      5
1   2    B      4
2   3    C      3
3   4    D      5
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [ ]:
pd.concat([df1,df2], axis = 1)

   ID Name  Class  ID Name  Class
0   1    A      5   5    E      9
1   2    B      4   6    F     10
2   3    C      3   7    G     11
3   4    D      5   8    H     12

In [ ]:
pd.concat([df2,df1], axis = 0)

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12
0   1    A      5
1   2    B      4
2   3    C      3
3   4    D      5

In [ ]:
pd.concat([df1,df2], axis = 0, ignore_index = True)

   ID Name  Class
0   1    A      5
1   2    B      4
2   3    C      3
3   4    D      5
4   5    E      9
5   6    F     10
6   7    G     11
7   8    H     12